name: 'Build & Test Solution'
on: 
  workflow_call:
jobs:
  build:
    name: 'Build solution'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "src\Mikkelhm.sln"
    - name: Build
      run: dotnet build "src\Mikkelhm.sln" --no-restore