name: Umbraco Cloud Sync

on:

  workflow_call:
    inputs: 
      projectId: 
        required: true
        type: string
    secrets:
      umbracoCloudApiKey:
        required: true
  
env:
  projectId: ${{ inputs.projectId }}
  umbracoCloudApiKey: ${{ secrets.umbracoCloudApiKey }}

jobs:
  preflight:
    name: Preflight checks
    environment: Umbraco Cloud
    runs-on: ubuntu-latest
    steps:
      # Gets the latest CICD Flow deployment if there is any
      # Will write "latestDeploymentId" to pipeline variables, value can be an uuid or empty string 
      - uses: actions/checkout@v3
      - name: Get Latest Deployment
        id: latest-deployment
        shell: pwsh
        run: >
          ${{GITHUB.WORKSPACE}}/.github/workflows/powershell/Get-LatestDeployment.ps1 
          -ProjectId ${{ env.projectId }} 
          -ApiKey ${{ env.umbracoCloudApiKey }} 
          -PipelineVendor GITHUB
    outputs: 
      latestDeployemntId: ${{ steps.latest-deployment.outputs.latestDeploymentId }}

  checkForChanges:
    name: Check if there are changes since latest deployment
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Download git-patch file based on latest deployment
      # Will write "remoteChanges" to pipeline variables, value can be "yes" or "no"
      # When "remoteChanges" is yes, there will also be downloaded a patch-file to the path you specified in -DownloadFolder parameter
      - name: Fetch Changes From Cloud
        env:
          latestDeploymentId: ${{ needs.preflight.outputs.latestDeployemntId }}
        if: ${{ env.latestDeploymentId != '' }}
        id: latest-changes
        shell: pwsh
        run: >
          ${{GITHUB.WORKSPACE}}/.github/workflows/powershell/Get-ChangesById.ps1 
          -ProjectId ${{ env.projectId }} 
          -ApiKey ${{ env.umbracoCloudApiKey }} 
          -DeploymentId ${{ env.latestDeploymentId }}
          -DownloadFolder ${{GITHUB.WORKSPACE}}/patch
          -PipelineVendor GITHUB

      - name: See diff content if any
        if: ${{ steps.latest-changes.outputs.remoteChanges == 'yes' }}
        shell: pwsh
        run: get-content ${{GITHUB.WORKSPACE}}/patch/git-patch.diff

      - name: Store diff before applying
        if: ${{ steps.latest-changes.outputs.remoteChanges == 'yes' }}
        id: store-git-patch
        uses: actions/upload-artifact@v3
        with:
          name: git-patch
          path: ${{GITHUB.WORKSPACE}}/patch/git-patch.diff
          retention-days: 1
    outputs:
      remoteChanges: ${{ steps.latest-changes.outputs.remoteChanges }}  

  applyRemoteChanges:
    name: Apply remote changes
    needs: [preflight, checkForChanges]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          remoteChanges: ${{ needs.checkForChanges.outputs.remoteChanges }}
        if: ${{ env.remoteChanges == 'yes' }}
        with:
          fetch-depth: 0

      - name: Get stored diff
        env:
          remoteChanges: ${{ needs.checkForChanges.outputs.remoteChanges }}
        if: ${{ env.remoteChanges == 'yes' }}
        uses: actions/download-artifact@v3
        with:
          name: git-patch
          path: ${{GITHUB.WORKSPACE}}/patch
      
      # Using plain git to try an push changes back to local repo
      # Depending on your setup you may need to change settings and permissions to better fit your needs
      # This targets the same branch as the pipeline was triggered on.
      # Stopping a new pipeline run by using the "[skip ci]" as part of commit message 
      - name: Applying git patch to branch
        env:
          remoteChanges: ${{ needs.checkForChanges.outputs.remoteChanges }}
          latestDeploymentId: ${{ needs.preflight.outputs.latestDeployemntId }}
        if: ${{ env.remoteChanges == 'yes' }}
        id: apply-git-patch
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git apply -v ${{GITHUB.WORKSPACE}}/patch/git-patch.diff
          git add *
          git commit -m "Adding cloud changes since deployment ${{ env.latestDeploymentId }} [skip ci]"
          git push

      - name: Approve git patch issues
        if: steps.apply-git-patch.outcome != 'success'
        env:
          latestDeploymentId: ${{ needs.preflight.outputs.latestDeployemntId }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mikkelhm
          minimum-approvals: 1
          issue-title: "Applying git patch for deployment with id ${{ env.latestDeploymentId }} failed"
          issue-body: |
            Please approve or deny the deployment with Id ${{ env.latestDeploymentId }}
            The deployment had issues applying the git patch changes - This could be caused by the merge had already happened on this
            local repository previously, or theres simply a merge conflict that needs to be solved.
            If the patch should just be ignored, please just approvce this issue. Else reject it.
            The git patch can be found here: ${{needs.checkForChanges.store-git-patch.outputs.artifact-url}}
          exclude-workflow-initiator-as-approver: false